import { NextRequest, NextResponse } from 'next/server';

const PROTECTED = ['/admin', '/kitchen', '/cook'];

export function middleware(request: NextRequest) {
    const { pathname } = request.nextUrl;
    const isProtected = PROTECTED.some(p => pathname.startsWith(p));

    if (isProtected) {
        const session = request.cookies.get('admin_session')?.value;
        // Session tokens are 64-char hex strings generated by the login route.
        // The old static 'authenticated' value is intentionally invalid here so
        // pre-deploy sessions force a re-login and create a tracked session record.
        if (!session || !/^[0-9a-f]{64}$/.test(session)) {
            return NextResponse.redirect(new URL('/login', request.url));
        }
    }

    return NextResponse.next();
}

export const config = {
    matcher: [
        '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
    ],
};
